Sklep/Sklep/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sklep.Models
{
    public class Category
    {
        public int CategoryID { get; set; }

        public string Name { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

Sklep/Sklep/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sklep.Models;

namespace Sklep.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        public ActionResult AllCategories()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            var query = category.Products.Select(b => b.Name + " - " + b.Price + "zł");
            ViewBag.Products = query.ToList();

            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sklep/Sklep/Controllers/PdfGenerationController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExportToExcel.Domain;
using Sklep.Models;
using System.Data.Entity;
using System.Net;

namespace ExportToExcel.Controllers
{
    public class PdfGenerationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PdfGeneration
        public ActionResult GeneratePdf(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            var query = category.Products.Select(b => b.Name + " - " + b.Price + " PLN");
            ViewBag.Products = query.ToList();

            return View(category);
        }

        [HttpPost]
        public ActionResult GeneratePdf(int? id, string heading, string paragraph)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            var query = category.Products.Select(b => b.Name + " - " + b.Price + " PLN");
            ViewBag.Products = query.ToList();

            PdfUtil objPdf = new PdfUtil();

            string path = Server.MapPath("~/Reports/price-list.pdf");
            if (!Directory.Exists(Server.MapPath("~/Reports")))
                Directory.CreateDirectory(Server.MapPath("~/Reports"));


            iTextSharp.text.Rectangle pagesize = new iTextSharp.text.Rectangle(20, 20, PageSize.A4.Width, PageSize.A4.Height);
            Document doc = new Document(pagesize, 50, 50, 50, 50);
            MemoryStream ms = new MemoryStream();
            PdfWriter pw = PdfWriter.GetInstance(doc, ms);
            doc.Open();

            doc.Add(objPdf.AddParagraphHeader(heading));
            doc.Add(objPdf.AddParagragh(paragraph));

            doc.Close();
            byte[] byteArray = ms.ToArray();
            ms.Flush();
            ms.Close();
            ms.Dispose();
            Response.Clear();
            Response.AddHeader("Content-Disposition", "attachment; filename=price-list.pdf");
            Response.AddHeader("Content-Length", byteArray.Length.ToString());
            Response.ContentType = "application/octet-stream";
            Response.BinaryWrite(byteArray);
            return View(category);
        }
    }
}

Sklep/Sklep/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sklep.Models;
using System.Globalization;
using PagedList;
using Microsoft.AspNet.Identity;
using System.Web.Helpers;
using System.Drawing;

namespace Sklep.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        public ActionResult ShowImage(int id)
        {
            Product product = db.Products.Find(id);
            var imageData = product.Image;
            FileContentResult result = null;
            try { result = File(imageData, "image/jpg"); } catch { }
            if (result != null) return result;
            else return File("~/img/square.png", "image/jpg");
        }

        public ActionResult ShowBigImage(int id)
        {
            Product product = db.Products.Find(id);
            var imageData = product.BigImage;
            FileContentResult result = null;
            try { result = File(imageData, "image/jpg"); } catch { }
            if (result != null) return result;
            else return File("~/img/square.png", "image/jpg");
        }

        public ActionResult AllProducts(string searchString, string keyWord, string producer, string priceFrom, string priceTo, string category, string sortOrder, int page=1)
        {
            var products = db.Products.Include(p => p.Category);
            var categories = db.Categories;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.Name.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(keyWord))
            {
                products = products.Where(p => p.Name.Contains(keyWord)
                               || p.Description.Contains(keyWord));
            }

            if (category != "---")
            {
                try
                {
                    int catID = int.Parse(category);
                    products = products.Where(p => p.CategoryID == catID);
                }
                catch { }
            }   

            if (!String.IsNullOrEmpty(producer))
            {
                products = products.Where(p => p.Producer.Contains(producer));
            }

            if (!String.IsNullOrEmpty(priceFrom))
            {
                float floatPriceFrom = float.Parse(priceFrom, CultureInfo.InvariantCulture);
                products = products.Where(p => p.Price >= floatPriceFrom);
            }

            if (!String.IsNullOrEmpty(priceTo))
            {
                float floatPriceTo = float.Parse(priceTo, CultureInfo.InvariantCulture);
                products = products.Where(p => p.Price <= floatPriceTo);
            }

            ViewBag.Category = new SelectList(db.Categories, "CategoryID", "Name");

            products = products.OrderByDescending(s => s.Name);
            int pageSize;

            var userId = User.Identity.GetUserId();
            var currentUser = db.Users.FirstOrDefault(p => p.Id == userId);
            if (currentUser == null) { pageSize = 10; }
            else pageSize = currentUser.ProductsOnPage;

            if (pageSize == 0)
            {
                pageSize = 10;
                currentUser.ProductsOnPage = 10;
                db.SaveChanges();
            }

            PagedList<Product> model = new PagedList<Product>(products, page, pageSize);

            return View(model);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if(product!=null) ViewBag.Description = product.Description;
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Image,BigImage")] Product product, HttpPostedFileBase image, HttpPostedFileBase bigImage)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    WebImage img = new WebImage(image.InputStream);
                    if (img.Width > 500 || img.Height > 500)
                        img.Resize(500, 500);
                    byte[] obrazek = img.GetBytes();
                    product.Image = obrazek;
                }
                if (bigImage != null)
                {
                    WebImage img1 = new WebImage(bigImage.InputStream);
                    if (img1.Width > 800 || img1.Height > 800)
                        img1.Resize(800, 800);
                    byte[] obrazek1 = img1.GetBytes();
                    product.BigImage = obrazek1;
                }

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);

            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "Image,BigImage")] Product product, HttpPostedFileBase image, HttpPostedFileBase bigImage, bool deleteImage = false, bool deleteBigImage = false)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;

                if (deleteImage == true) product.Image = null;
                if (deleteBigImage == true) product.BigImage = null;

                if (image != null)
                {
                    WebImage img = new WebImage(image.InputStream);
                    if (img.Width > 500 || img.Height > 500)
                        img.Resize(500, 500);
                    byte[] obrazek = img.GetBytes();
                    product.Image = obrazek;
                }
                else
                {
                    db.Entry(product).Property(m => m.Image).IsModified = false;
                }
                if (deleteImage == true) db.Entry(product).Property(m => m.Image).IsModified = true;

                if (bigImage != null)
                {
                    WebImage img1 = new WebImage(bigImage.InputStream);
                    if (img1.Width > 800 || img1.Height > 800)
                        img1.Resize(800, 800);
                    byte[] obrazek1 = img1.GetBytes();
                    product.BigImage = obrazek1;
                }
                else
                {
                    db.Entry(product).Property(m => m.BigImage).IsModified = false;
                }
                if (deleteBigImage == true) db.Entry(product).Property(m => m.BigImage).IsModified = true;

            db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sklep/Sklep/Views/Categories/AllCategories.cshtml
@model IEnumerable<Sklep.Models.Category>

@{
    ViewBag.Title = "Categories";
}

<h2>Categories</h2>

<hr />

<ul>
    @foreach (var item in Model)
    {
        <li class="categoryList">
            @Html.ActionLink(item.Name, "AllProducts", "Products", new { Category = item.CategoryID }, new { @class = "link" })
            &nbsp;
            @Html.ActionLink("Get price list >>", "GeneratePdf", "PdfGeneration", new { id = item.CategoryID }, new { @class = "btn btn-default btn-sm" })
        </li>
    }
</ul>

Sklep/Sklep/Views/Categories/Create.cshtml
@model Sklep.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sklep/Sklep/Views/Categories/Delete.cshtml
@model Sklep.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sklep/Sklep/Views/Categories/Details.cshtml
@model Sklep.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Products
        </dt>

        <dd>
            <ul>
                @foreach (var item in ViewBag.Products)
                {
                    <li>@item</li>
                }
            </ul>
        </dd>

    </dl>

</div>

Sklep/Sklep/Views/Categories/Edit.cshtml
@model Sklep.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sklep/Sklep/Views/Categories/Index.cshtml
@model IEnumerable<Sklep.Models.Category>

@{
    ViewBag.Title = "Categories";
}

<h2>Categories</h2>

<a href="@Url.Action("Create", "Categories")"><span class="btn btn-primary pull-right"><i class="fa fa-plus"></i> create new</span></a>

<br /><br />

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 rowSpace"></div>

@foreach (var item in Model)
{
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 indexItemBackground">
    <div class="mb10 mr35 inlineBlock">
        <span class="bold">ID:</span> @Html.DisplayFor(modelItem => item.CategoryID)
    </div>
    <div class="mb10 mr35 inlineBlock">
        <span class="bold">Name:</span> @Html.DisplayFor(modelItem => item.Name)
    </div>
    <div class="col-lg-4 col-md-5 col-sm-12 col-xs-12 pull-right">
        <span class="btn btn-success mb5 pull-right"><i class="fa fa-file-pdf-o"></i> @Html.ActionLink("PDF", "GeneratePdf", "PdfGeneration", new { id = item.CategoryID }, new { @class = "linkDecorationNone" })</span>
        <a href="@Url.Action("Delete", "Categories", new { id = item.CategoryID })"><span class="btn btn-danger mb5 mr5 pull-right"><i class="fa fa-remove"></i> delete</span></a>
        <a href="@Url.Action("Edit", "Categories", new { id = item.CategoryID })"><span class="btn btn-warning mb5 mr5 pull-right"><i class="fa fa-wrench"></i> edit</span></a>
        <a href="@Url.Action("Details", "Categories", new { id = item.CategoryID })"><span class="btn btn-info mb5 mr5 pull-right"><i class="fa fa-calendar"></i> details</span></a>
    </div>
</div>
}